language: objective-c
xcode_workspace: Conferences.xcworkspace
xcode_scheme: ConferencesTests
osx_image: xcode7.2
script:
  - xctool test -workspace Conferences.xcworkspace -scheme ConferencesTests -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.1" ONLY_ACTIVE_ARCH=YES