language: objective-c
osx_image: xcode7.3
branches:
  only:
  - master
  - develop
script: scan --scheme "ConferencesTests"
before_install:
- gem update --system
- gem --version
- gem install fastlane
