language: objective-c
osx_image: xcode7.2
before_install:
    - brew update
    - brew install xctool
script:
  - xctool test -workspace Conferences.xcworkspace -scheme ConferencesTests -configuration Debug -test-sdk iphonesimulator9.2 ONLY_ACTIVE_ARCH=YES